[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
fastapi = "^0.128.0"
sqlalchemy = "^2.0.46"
pydantic = "^2.12.5"
pydantic-settings = "^2.12.0"
alembic = "^1.18.1"
uvicorn = "^0.40.0"



[dependency-groups]
dev = [
    "black (>=26.1.0,<27.0.0)"
]
